# Site settings
title: Hamed ghoorchiani
email: hamedghnov91@gmail.com
description: توسعه‌دهنده رابط کاربری
baseurl: "http://hamedgh.ir/"
url: "http://hamedgh.ir"
twitter: _ghoorchiani
github:  hamednov1991
behance: hamednov1991
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]

